# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd]

if GetDepend(['USB_SERIAL_DEVICE_ENABLE_HOST']):
    src += Glob('dev_usbh_serial.c')

group = DefineGroup('USBSerialDevice', src, depend = ['RT_USING_USB_SERIAL_DEVICE'], CPPPATH = CPPPATH)

objs = [group]

Return('objs')