# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')

CPPPATH = [cwd]

group = DefineGroup('RotaryKnob', src, depend = ['ENABLE_ROTARY_KNOB'], CPPPATH = CPPPATH)

objs = [group]

Return('objs')
