from building import *

try:
    Import('romfs_obj')
except NameError:
    romfs_obj = None

cwd = GetCurrentDir()
CPPPATH = [cwd]

src	= Glob('main.c')
src	+= Glob('mnt.c')
src	+= Glob('config.c')

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

objs = [group]
list = os.listdir(cwd)

if GetDepend(['CONFIG_RTSMART_ENABLE_ROMFS']):
    Env.Depends(objs, romfs_obj)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
