# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('DeviceWarp', src, depend = ['RT_USING_DEVICE_WRAP'], CPPPATH = CPPPATH)

objs = [group]

Return('objs')
