# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')

CPPPATH = [cwd]

group = DefineGroup('Terminal', src, depend = ['ENABLE_TERMINAL'], CPPPATH = CPPPATH)

objs = [group]

Return('objs')
